# Generated by Django 5.1.6 on 2025-05-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_article_headerimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='headerImage',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/blog_header_images'),
        ),
    ]
