# Generated by Django 5.1.6 on 2025-03-07 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['created_on']},
        ),
        migrations.RenameField(
            model_name='commission',
            old_name='entry',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='commission',
            old_name='last_updated',
            new_name='updated_on',
        ),
        migrations.AddField(
            model_name='commission',
            name='people_required',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('commission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commissions.commission')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.DeleteModel(
            name='CommissionCategory',
        ),
    ]
