# Generated by Django 5.2.1 on 2025-05-20 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_commission_author_commission_status_and_more'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-status', '-manpower_required', 'role']},
        ),
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['status', '-applied_on']},
        ),
        migrations.RemoveField(
            model_name='commission',
            name='people_required',
        ),
        migrations.AlterField(
            model_name='commission',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='commissions_authored', to='user_management.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commission',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('F', 'Full'), ('C', 'Completed'), ('D', 'Discontinued')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='commission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='commissions.commission'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='manpower_required',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('F', 'Full')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='applicant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='user_management.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='commissions.job'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Accepted'), ('3', 'Rejected')], default='1', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('job', 'applicant')},
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
