# Generated by Django 5.1.6 on 2025-05-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_headerimage_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='headerImage',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='blog_header_images/'),
        ),
    ]
