# Generated by Django 5.2.1 on 2025-05-14 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_galleryimage_delete_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
