# Generated by Django 5.1.6 on 2025-05-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_author_alter_comment_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='headerImage',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/blog_header_images/'),
        ),
    ]
